// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: authenticator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SigType int32

const (
	SigType_PKSig SigType = 0
	SigType_MAC   SigType = 1
)

// Enum value maps for SigType.
var (
	SigType_name = map[int32]string{
		0: "PKSig",
		1: "MAC",
	}
	SigType_value = map[string]int32{
		"PKSig": 0,
		"MAC":   1,
	}
)

func (x SigType) Enum() *SigType {
	p := new(SigType)
	*p = x
	return p
}

func (x SigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SigType) Descriptor() protoreflect.EnumDescriptor {
	return file_authenticator_proto_enumTypes[0].Descriptor()
}

func (SigType) Type() protoreflect.EnumType {
	return &file_authenticator_proto_enumTypes[0]
}

func (x SigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SigType.Descriptor instead.
func (SigType) EnumDescriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0}
}

type Authenticator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    int32                  `protobuf:"varint,1,opt,name=fromNodeId,proto3" json:"fromNodeId,omitempty"`
	ToNodeId      int32                  `protobuf:"varint,2,opt,name=toNodeId,proto3" json:"toNodeId,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	SigType       SigType                `protobuf:"varint,4,opt,name=sigType,proto3,enum=bftmessages.SigType" json:"sigType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	mi := &file_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *Authenticator) GetFromNodeId() int32 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *Authenticator) GetToNodeId() int32 {
	if x != nil {
		return x.ToNodeId
	}
	return 0
}

func (x *Authenticator) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Authenticator) GetSigType() SigType {
	if x != nil {
		return x.SigType
	}
	return SigType_PKSig
}

var File_authenticator_proto protoreflect.FileDescriptor

const file_authenticator_proto_rawDesc = "" +
	"\n" +
	"\x13authenticator.proto\x12\vbftmessages\"\x8d\x01\n" +
	"\rAuthenticator\x12\x1e\n" +
	"\n" +
	"fromNodeId\x18\x01 \x01(\x05R\n" +
	"fromNodeId\x12\x1a\n" +
	"\btoNodeId\x18\x02 \x01(\x05R\btoNodeId\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\x12.\n" +
	"\asigType\x18\x04 \x01(\x0e2\x14.bftmessages.SigTypeR\asigType*\x1d\n" +
	"\aSigType\x12\t\n" +
	"\x05PKSig\x10\x00\x12\a\n" +
	"\x03MAC\x10\x01B\x1aZ\x18github.com/zistvan/protob\x06proto3"

var (
	file_authenticator_proto_rawDescOnce sync.Once
	file_authenticator_proto_rawDescData []byte
)

func file_authenticator_proto_rawDescGZIP() []byte {
	file_authenticator_proto_rawDescOnce.Do(func() {
		file_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authenticator_proto_rawDesc), len(file_authenticator_proto_rawDesc)))
	})
	return file_authenticator_proto_rawDescData
}

var file_authenticator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authenticator_proto_goTypes = []any{
	(SigType)(0),          // 0: bftmessages.SigType
	(*Authenticator)(nil), // 1: bftmessages.Authenticator
}
var file_authenticator_proto_depIdxs = []int32{
	0, // 0: bftmessages.Authenticator.sigType:type_name -> bftmessages.SigType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authenticator_proto_init() }
func file_authenticator_proto_init() {
	if File_authenticator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authenticator_proto_rawDesc), len(file_authenticator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authenticator_proto_goTypes,
		DependencyIndexes: file_authenticator_proto_depIdxs,
		EnumInfos:         file_authenticator_proto_enumTypes,
		MessageInfos:      file_authenticator_proto_msgTypes,
	}.Build()
	File_authenticator_proto = out.File
	file_authenticator_proto_goTypes = nil
	file_authenticator_proto_depIdxs = nil
}
