// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: peer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_ClientRequest     MsgType = 0
	MsgType_ClientResponse    MsgType = 1
	MsgType_PrePrepare        MsgType = 2
	MsgType_Prepare           MsgType = 3
	MsgType_Commit            MsgType = 4
	MsgType_Checkpoint        MsgType = 5
	MsgType_Probe             MsgType = 6
	MsgType_ProbeAck          MsgType = 7
	MsgType_NewConfig         MsgType = 8
	MsgType_SyncState         MsgType = 9
	MsgType_ClusterPrePrepare MsgType = 10
	MsgType_ClusterPrepare    MsgType = 11
	MsgType_ClusterCommit     MsgType = 12
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "ClientRequest",
		1:  "ClientResponse",
		2:  "PrePrepare",
		3:  "Prepare",
		4:  "Commit",
		5:  "Checkpoint",
		6:  "Probe",
		7:  "ProbeAck",
		8:  "NewConfig",
		9:  "SyncState",
		10: "ClusterPrePrepare",
		11: "ClusterPrepare",
		12: "ClusterCommit",
	}
	MsgType_value = map[string]int32{
		"ClientRequest":     0,
		"ClientResponse":    1,
		"PrePrepare":        2,
		"Prepare":           3,
		"Commit":            4,
		"Checkpoint":        5,
		"Probe":             6,
		"ProbeAck":          7,
		"NewConfig":         8,
		"SyncState":         9,
		"ClusterPrePrepare": 10,
		"ClusterPrepare":    11,
		"ClusterCommit":     12,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_peer_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

type PeerMessage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId             int32                  `protobuf:"varint,1,opt,name=fromNodeId,proto3" json:"fromNodeId,omitempty"`
	MsgId                  int32                  `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	EpochId                int32                  `protobuf:"varint,3,opt,name=epochId,proto3" json:"epochId,omitempty"`
	Type                   MsgType                `protobuf:"varint,4,opt,name=type,proto3,enum=bftmessages.MsgType" json:"type,omitempty"`
	AttachedData           []byte                 `protobuf:"bytes,5,opt,name=attachedData,proto3" json:"attachedData,omitempty"`
	Auth                   []*Authenticator       `protobuf:"bytes,6,rep,name=auth,proto3" json:"auth,omitempty"`
	Certificate            []*ClusterCertificate  `protobuf:"bytes,7,rep,name=certificate,proto3" json:"certificate,omitempty"`
	CompressedCertificates []byte                 `protobuf:"bytes,8,opt,name=compressedCertificates,proto3" json:"compressedCertificates,omitempty"`
	ClusterId              int32                  `protobuf:"varint,9,opt,name=clusterId,proto3" json:"clusterId,omitempty"`
	MessageSizes           []int32                `protobuf:"varint,10,rep,packed,name=MessageSizes,proto3" json:"MessageSizes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PeerMessage) Reset() {
	*x = PeerMessage{}
	mi := &file_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMessage) ProtoMessage() {}

func (x *PeerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMessage.ProtoReflect.Descriptor instead.
func (*PeerMessage) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{0}
}

func (x *PeerMessage) GetFromNodeId() int32 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *PeerMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PeerMessage) GetEpochId() int32 {
	if x != nil {
		return x.EpochId
	}
	return 0
}

func (x *PeerMessage) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_ClientRequest
}

func (x *PeerMessage) GetAttachedData() []byte {
	if x != nil {
		return x.AttachedData
	}
	return nil
}

func (x *PeerMessage) GetAuth() []*Authenticator {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *PeerMessage) GetCertificate() []*ClusterCertificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *PeerMessage) GetCompressedCertificates() []byte {
	if x != nil {
		return x.CompressedCertificates
	}
	return nil
}

func (x *PeerMessage) GetClusterId() int32 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *PeerMessage) GetMessageSizes() []int32 {
	if x != nil {
		return x.MessageSizes
	}
	return nil
}

type ClusterCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    int32                  `protobuf:"varint,2,opt,name=fromNodeId,proto3" json:"fromNodeId,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCertificate) Reset() {
	*x = ClusterCertificate{}
	mi := &file_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCertificate) ProtoMessage() {}

func (x *ClusterCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCertificate.ProtoReflect.Descriptor instead.
func (*ClusterCertificate) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterCertificate) GetFromNodeId() int32 {
	if x != nil {
		return x.FromNodeId
	}
	return 0
}

func (x *ClusterCertificate) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type CertificateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Initialized   bool                   `protobuf:"varint,1,opt,name=initialized,proto3" json:"initialized,omitempty"`
	CntPrepared   int32                  `protobuf:"varint,2,opt,name=cntPrepared,proto3" json:"cntPrepared,omitempty"`
	Certificates  []*PeerMessage         `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateMessage) Reset() {
	*x = CertificateMessage{}
	mi := &file_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateMessage) ProtoMessage() {}

func (x *CertificateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateMessage.ProtoReflect.Descriptor instead.
func (*CertificateMessage) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{2}
}

func (x *CertificateMessage) GetInitialized() bool {
	if x != nil {
		return x.Initialized
	}
	return false
}

func (x *CertificateMessage) GetCntPrepared() int32 {
	if x != nil {
		return x.CntPrepared
	}
	return 0
}

func (x *CertificateMessage) GetCertificates() []*PeerMessage {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type PayloadNewConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []int32                `protobuf:"varint,1,rep,packed,name=members,proto3" json:"members,omitempty"`
	Leader        int32                  `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	DigestState   []byte                 `protobuf:"bytes,3,opt,name=digestState,proto3" json:"digestState,omitempty"`
	DigestP       []byte                 `protobuf:"bytes,4,opt,name=digestP,proto3" json:"digestP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadNewConfig) Reset() {
	*x = PayloadNewConfig{}
	mi := &file_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadNewConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadNewConfig) ProtoMessage() {}

func (x *PayloadNewConfig) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadNewConfig.ProtoReflect.Descriptor instead.
func (*PayloadNewConfig) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{3}
}

func (x *PayloadNewConfig) GetMembers() []int32 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *PayloadNewConfig) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *PayloadNewConfig) GetDigestState() []byte {
	if x != nil {
		return x.DigestState
	}
	return nil
}

func (x *PayloadNewConfig) GetDigestP() []byte {
	if x != nil {
		return x.DigestP
	}
	return nil
}

type PayloadSyncState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Clients          []int32                `protobuf:"varint,1,rep,packed,name=clients,proto3" json:"clients,omitempty"`
	Certificate      *CertificateMessage    `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	NewConfigMessage *PeerMessage           `protobuf:"bytes,3,opt,name=newConfigMessage,proto3" json:"newConfigMessage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PayloadSyncState) Reset() {
	*x = PayloadSyncState{}
	mi := &file_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadSyncState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadSyncState) ProtoMessage() {}

func (x *PayloadSyncState) ProtoReflect() protoreflect.Message {
	mi := &file_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadSyncState.ProtoReflect.Descriptor instead.
func (*PayloadSyncState) Descriptor() ([]byte, []int) {
	return file_peer_proto_rawDescGZIP(), []int{4}
}

func (x *PayloadSyncState) GetClients() []int32 {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *PayloadSyncState) GetCertificate() *CertificateMessage {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *PayloadSyncState) GetNewConfigMessage() *PeerMessage {
	if x != nil {
		return x.NewConfigMessage
	}
	return nil
}

var File_peer_proto protoreflect.FileDescriptor

const file_peer_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"peer.proto\x12\vbftmessages\x1a\x13authenticator.proto\"\x98\x03\n" +
	"\vPeerMessage\x12\x1e\n" +
	"\n" +
	"fromNodeId\x18\x01 \x01(\x05R\n" +
	"fromNodeId\x12\x14\n" +
	"\x05msgId\x18\x02 \x01(\x05R\x05msgId\x12\x18\n" +
	"\aepochId\x18\x03 \x01(\x05R\aepochId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.bftmessages.MsgTypeR\x04type\x12\"\n" +
	"\fattachedData\x18\x05 \x01(\fR\fattachedData\x12.\n" +
	"\x04auth\x18\x06 \x03(\v2\x1a.bftmessages.AuthenticatorR\x04auth\x12A\n" +
	"\vcertificate\x18\a \x03(\v2\x1f.bftmessages.ClusterCertificateR\vcertificate\x126\n" +
	"\x16compressedCertificates\x18\b \x01(\fR\x16compressedCertificates\x12\x1c\n" +
	"\tclusterId\x18\t \x01(\x05R\tclusterId\x12\"\n" +
	"\fMessageSizes\x18\n" +
	" \x03(\x05R\fMessageSizes\"F\n" +
	"\x12ClusterCertificate\x12\x1e\n" +
	"\n" +
	"fromNodeId\x18\x02 \x01(\x05R\n" +
	"fromNodeId\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\"\x96\x01\n" +
	"\x12CertificateMessage\x12 \n" +
	"\vinitialized\x18\x01 \x01(\bR\vinitialized\x12 \n" +
	"\vcntPrepared\x18\x02 \x01(\x05R\vcntPrepared\x12<\n" +
	"\fcertificates\x18\x03 \x03(\v2\x18.bftmessages.PeerMessageR\fcertificates\"\x80\x01\n" +
	"\x10PayloadNewConfig\x12\x18\n" +
	"\amembers\x18\x01 \x03(\x05R\amembers\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\x05R\x06leader\x12 \n" +
	"\vdigestState\x18\x03 \x01(\fR\vdigestState\x12\x18\n" +
	"\adigestP\x18\x04 \x01(\fR\adigestP\"\xb5\x01\n" +
	"\x10PayloadSyncState\x12\x18\n" +
	"\aclients\x18\x01 \x03(\x05R\aclients\x12A\n" +
	"\vcertificate\x18\x02 \x01(\v2\x1f.bftmessages.CertificateMessageR\vcertificate\x12D\n" +
	"\x10newConfigMessage\x18\x03 \x01(\v2\x18.bftmessages.PeerMessageR\x10newConfigMessage*\xde\x01\n" +
	"\aMsgType\x12\x11\n" +
	"\rClientRequest\x10\x00\x12\x12\n" +
	"\x0eClientResponse\x10\x01\x12\x0e\n" +
	"\n" +
	"PrePrepare\x10\x02\x12\v\n" +
	"\aPrepare\x10\x03\x12\n" +
	"\n" +
	"\x06Commit\x10\x04\x12\x0e\n" +
	"\n" +
	"Checkpoint\x10\x05\x12\t\n" +
	"\x05Probe\x10\x06\x12\f\n" +
	"\bProbeAck\x10\a\x12\r\n" +
	"\tNewConfig\x10\b\x12\r\n" +
	"\tSyncState\x10\t\x12\x15\n" +
	"\x11ClusterPrePrepare\x10\n" +
	"\x12\x12\n" +
	"\x0eClusterPrepare\x10\v\x12\x11\n" +
	"\rClusterCommit\x10\fB\x1aZ\x18github.com/zistvan/protob\x06proto3"

var (
	file_peer_proto_rawDescOnce sync.Once
	file_peer_proto_rawDescData []byte
)

func file_peer_proto_rawDescGZIP() []byte {
	file_peer_proto_rawDescOnce.Do(func() {
		file_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)))
	})
	return file_peer_proto_rawDescData
}

var file_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_peer_proto_goTypes = []any{
	(MsgType)(0),               // 0: bftmessages.MsgType
	(*PeerMessage)(nil),        // 1: bftmessages.PeerMessage
	(*ClusterCertificate)(nil), // 2: bftmessages.ClusterCertificate
	(*CertificateMessage)(nil), // 3: bftmessages.CertificateMessage
	(*PayloadNewConfig)(nil),   // 4: bftmessages.PayloadNewConfig
	(*PayloadSyncState)(nil),   // 5: bftmessages.PayloadSyncState
	(*Authenticator)(nil),      // 6: bftmessages.Authenticator
}
var file_peer_proto_depIdxs = []int32{
	0, // 0: bftmessages.PeerMessage.type:type_name -> bftmessages.MsgType
	6, // 1: bftmessages.PeerMessage.auth:type_name -> bftmessages.Authenticator
	2, // 2: bftmessages.PeerMessage.certificate:type_name -> bftmessages.ClusterCertificate
	1, // 3: bftmessages.CertificateMessage.certificates:type_name -> bftmessages.PeerMessage
	3, // 4: bftmessages.PayloadSyncState.certificate:type_name -> bftmessages.CertificateMessage
	1, // 5: bftmessages.PayloadSyncState.newConfigMessage:type_name -> bftmessages.PeerMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_peer_proto_init() }
func file_peer_proto_init() {
	if File_peer_proto != nil {
		return
	}
	file_authenticator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_peer_proto_rawDesc), len(file_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peer_proto_goTypes,
		DependencyIndexes: file_peer_proto_depIdxs,
		EnumInfos:         file_peer_proto_enumTypes,
		MessageInfos:      file_peer_proto_msgTypes,
	}.Build()
	File_peer_proto = out.File
	file_peer_proto_goTypes = nil
	file_peer_proto_depIdxs = nil
}
